<a href="https://colab.research.google.com/github/kesava2001/pytorch-basics/blob/main/pytorch_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 

In [2]:
x = [1,2,3,4,5,6,7]

torch.is_tensor(x) #this returns a false because, here x is not a tensor object

False

In [3]:
y = torch.randn(3,3,3)

torch.is_tensor(y)
torch.numel(y) #this return the total number of elements in a tensor(3*3*3 here)

27

In [4]:
#creating a tensor of zeros/ones

z = torch.ones(4,4)

z

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
p = torch.eye(4,4)
p #gives a tensor with diagonal elements ones and off diagonal zeros

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [6]:
import numpy
x1 = numpy.array(x)
x2 = torch.from_numpy(x1) #converts numpy array to a tensor
x2

tensor([1, 2, 3, 4, 5, 6, 7])

In [7]:
ls = torch.linspace(1, 10, steps=30) #divides 1 to 10 into 30 parts of equal magnitude
ls

tensor([ 1.0000,  1.3103,  1.6207,  1.9310,  2.2414,  2.5517,  2.8621,  3.1724,
         3.4828,  3.7931,  4.1034,  4.4138,  4.7241,  5.0345,  5.3448,  5.6552,
         5.9655,  6.2759,  6.5862,  6.8966,  7.2069,  7.5172,  7.8276,  8.1379,
         8.4483,  8.7586,  9.0690,  9.3793,  9.6897, 10.0000])

In [8]:
#random numbers from a uniform distribution between 0 and 1
torch.rand(5)
#since these values are from uniform distribution they all have the same probability of occuring

tensor([0.7508, 0.8486, 0.8147, 0.5531, 0.2624])

In [9]:
torch.rand(3,4) #2 dimensional tensor

tensor([[0.4515, 0.1708, 0.4188, 0.1655],
        [0.5500, 0.2700, 0.6693, 0.2161],
        [0.7181, 0.9330, 0.2498, 0.5177]])

In [10]:
torch.randn(2,3) #random numbers from a normal distribution

tensor([[ 0.2913,  0.2464,  0.6508],
        [-0.4853,  1.1678,  2.2331]])

In [11]:
torch.randperm(7) #random integers are selected from the given range

tensor([0, 1, 3, 6, 4, 5, 2])

In [12]:
torch.arange(2,30) #integers between 2-30, excluding the terminal value

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
torch.arange(2,30, 3) #step is 3

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [14]:
d = torch.randn(3, 4)
d

tensor([[-0.8169, -0.1133, -0.8154,  0.1988],
        [-0.6616,  0.0494, -1.0150,  1.0718],
        [-2.1762,  0.6597, -1.6798,  0.4693]])

In [15]:
torch.argmin(d, dim=1) #returns index of minimum value of each row

tensor([0, 2, 0])

In [16]:
torch.argmax(d, dim=1) #returns index of maximum values in each row

tensor([3, 3, 1])

In [17]:
torch.cat((d, d), 0) #this the concatenation function by pytorch

tensor([[-0.8169, -0.1133, -0.8154,  0.1988],
        [-0.6616,  0.0494, -1.0150,  1.0718],
        [-2.1762,  0.6597, -1.6798,  0.4693],
        [-0.8169, -0.1133, -0.8154,  0.1988],
        [-0.6616,  0.0494, -1.0150,  1.0718],
        [-2.1762,  0.6597, -1.6798,  0.4693]])

In [18]:
torch.cat((d, d), 1) #this concats over columns

tensor([[-0.8169, -0.1133, -0.8154,  0.1988, -0.8169, -0.1133, -0.8154,  0.1988],
        [-0.6616,  0.0494, -1.0150,  1.0718, -0.6616,  0.0494, -1.0150,  1.0718],
        [-2.1762,  0.6597, -1.6798,  0.4693, -2.1762,  0.6597, -1.6798,  0.4693]])

In [19]:
b = torch.randn(6,6)

torch.chunk(b, 2, 0) # 0 chunks over rows

(tensor([[ 0.8164, -0.6719,  0.8148,  2.2231, -0.4117, -1.4655],
         [-1.5478, -0.3094, -0.3435, -2.0072,  0.7034, -0.2075],
         [-0.0232,  0.1480,  0.0456, -0.1950, -0.5604, -0.0108]]),
 tensor([[-2.0555,  1.6997,  0.9429, -0.8149, -0.3245, -0.1569],
         [-0.3705,  0.7918, -0.2983, -0.4461, -1.0502,  0.3812],
         [ 1.9484, -0.9057,  0.6075, -0.0093,  1.2991,  0.6602]]))

In [20]:
torch.chunk(b, 2, 1)
torch.chunk(b, 3, 0)
torch.chunk(b, 3, 1) # 1 chunks over columns

(tensor([[ 0.8164, -0.6719],
         [-1.5478, -0.3094],
         [-0.0232,  0.1480],
         [-2.0555,  1.6997],
         [-0.3705,  0.7918],
         [ 1.9484, -0.9057]]), tensor([[ 0.8148,  2.2231],
         [-0.3435, -2.0072],
         [ 0.0456, -0.1950],
         [ 0.9429, -0.8149],
         [-0.2983, -0.4461],
         [ 0.6075, -0.0093]]), tensor([[-0.4117, -1.4655],
         [ 0.7034, -0.2075],
         [-0.5604, -0.0108],
         [-0.3245, -0.1569],
         [-1.0502,  0.3812],
         [ 1.2991,  0.6602]]))

In [21]:
torch.chunk(b, 6, 1)

(tensor([[ 0.8164],
         [-1.5478],
         [-0.0232],
         [-2.0555],
         [-0.3705],
         [ 1.9484]]), tensor([[-0.6719],
         [-0.3094],
         [ 0.1480],
         [ 1.6997],
         [ 0.7918],
         [-0.9057]]), tensor([[ 0.8148],
         [-0.3435],
         [ 0.0456],
         [ 0.9429],
         [-0.2983],
         [ 0.6075]]), tensor([[ 2.2231],
         [-2.0072],
         [-0.1950],
         [-0.8149],
         [-0.4461],
         [-0.0093]]), tensor([[-0.4117],
         [ 0.7034],
         [-0.5604],
         [-0.3245],
         [-1.0502],
         [ 1.2991]]), tensor([[-1.4655],
         [-0.2075],
         [-0.0108],
         [-0.1569],
         [ 0.3812],
         [ 0.6602]]))

In [22]:
torch.gather(torch.Tensor([[1,2], [3,4]]), 0, torch.LongTensor([[0,1], [1,0]])) 
#after trying a few time my brain got messed up thinking what in the world is this function doing

tensor([[1., 4.],
        [3., 2.]])

In [23]:
c = torch.randn(4,4)

h = torch.LongTensor([0, 2]) #indices we want to select

torch.index_select(c, 1, h) # 0 for rows, 1 for columns

tensor([[ 0.1903, -1.5156],
        [-0.2855,  2.2588],
        [ 0.2770, -0.8783],
        [ 1.6374,  0.5795]])

In [24]:
torch.nonzero(torch.tensor([1,0,0,0,3,0,0,4,0,0])) #returns a tensor whose values are indices of nonzero elements

tensor([[0],
        [4],
        [7]])

In [25]:
torch.split(torch.tensor([1,7,9,4,12,45,90,43]), 3) #splits the tensor into specified number of chunks

(tensor([1, 7, 9]), tensor([ 4, 12, 45]), tensor([90, 43]))

In [33]:
s = torch.randn(3, 4)

print(s)

print(s.t()) #gives transpose of original tensor

print(s.transpose(1, 0))

tensor([[ 0.2209, -0.6249, -1.1739, -0.5135],
        [ 0.4791,  0.4981, -0.9259, -0.5209],
        [-1.2345, -0.2951,  0.2527, -0.7301]])
tensor([[ 0.2209,  0.4791, -1.2345],
        [-0.6249,  0.4981, -0.2951],
        [-1.1739, -0.9259,  0.2527],
        [-0.5135, -0.5209, -0.7301]])
tensor([[ 0.2209,  0.4791, -1.2345],
        [-0.6249,  0.4981, -0.2951],
        [-1.1739, -0.9259,  0.2527],
        [-0.5135, -0.5209, -0.7301]])


In [38]:
torch.unbind(s, 1) 
#gives row tensors from the given input tensor, if 1 is given as argument gives column tensors from given input 

(tensor([ 0.2209,  0.4791, -1.2345]),
 tensor([-0.6249,  0.4981, -0.2951]),
 tensor([-1.1739, -0.9259,  0.2527]),
 tensor([-0.5135, -0.5209, -0.7301]))

In [39]:
torch.add(s, 10) # adds the scalar to every element of the tensor

tensor([[10.2209,  9.3751,  8.8261,  9.4865],
        [10.4791, 10.4981,  9.0741,  9.4791],
        [ 8.7655,  9.7049, 10.2527,  9.2699]])

In [40]:
torch.mul(s, 10)

tensor([[  2.2089,  -6.2494, -11.7385,  -5.1345],
        [  4.7912,   4.9812,  -9.2589,  -5.2091],
        [-12.3445,  -2.9509,   2.5267,  -7.3005]])

In [43]:
intercept = torch.randn(1)

x = torch.randn(2,2)

beta = 0.75

y = torch.add(torch.mul(intercept, x), torch.mul(beta, x))

y

tensor([[1.1163, 0.4681],
        [0.1042, 0.1658]])

In [44]:
torch.manual_seed(23)

torch.ceil(torch.randn(5,5)), torch.floor(torch.randn(5,5)) 

(tensor([[-0.,  1., -0.,  1.,  1.],
         [-0., -0.,  1., -0., -0.],
         [-1.,  1., -2.,  1., -0.],
         [ 1., -0., -0., -1.,  2.],
         [ 1.,  1., -1., -1., -0.]]), tensor([[ 0.,  0., -1.,  0.,  1.],
         [-1.,  0., -1.,  0.,  1.],
         [-1., -1.,  1., -1., -1.],
         [-2.,  0., -2., -1.,  0.],
         [-2.,  1.,  0., -2., -2.]]))

In [48]:
torch.clamp((torch.randn(5,5)), max=0.5)

tensor([[-0.2853,  0.0851, -0.6661,  0.1910,  0.5000],
        [ 0.5000,  0.5000,  0.5000,  0.5000,  0.5000],
        [-0.3333, -0.3857,  0.0754,  0.0324,  0.5000],
        [-2.1172, -0.3549,  0.5000, -0.8069, -0.8732],
        [-0.6171, -0.5606, -2.4425, -1.0211, -0.1561]])

In [51]:
b = torch.exp(torch.rand(2,2))
b

tensor([[2.0485, 2.3108],
        [1.0590, 1.1192]])

In [52]:
torch.frac(b) #gives the fraction part of a tensor

tensor([[0.0485, 0.3108],
        [0.0590, 0.1192]])

In [53]:
torch.pow(b, 2) # this gives b**2

tensor([[4.1964, 5.3400],
        [1.1216, 1.2526]])

In [54]:
torch.log(torch.randn(2,2))

tensor([[-1.9240,     nan],
        [    nan, -1.0357]])

In [55]:
torch.sigmoid(b)

tensor([[0.8858, 0.9098],
        [0.7425, 0.7538]])

In [56]:
torch.sqrt(torch.randn(3,3))

tensor([[   nan, 0.7885, 0.7013],
        [   nan, 0.8788,    nan],
        [0.6771,    nan, 0.6832]])

In [58]:
torch.manual_seed(123)
torch.randn(3,3) # manual_seed is set to get the same random values from normal distribution

tensor([[-0.1115,  0.1204, -0.3696],
        [-0.2404, -1.1969,  0.2093],
        [-0.9724, -0.7550,  0.3239]])